// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameItemAdImages = "item_ad_images"

// ItemAdImages mapped from table <item_ad_images>
type ItemAdImages struct {
	ItemID    string `gorm:"column:item_id;type:TEXT" json:"item_id"`
	AdImageID string `gorm:"column:ad_image_id;type:TEXT" json:"ad_image_id"`
}

// TableName ItemAdImages's table name
func (*ItemAdImages) TableName() string {
	return TableNameItemAdImages
}
