// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameItemCategories = "item_categories"

// ItemCategories mapped from table <item_categories>
type ItemCategories struct {
	ItemID   string `gorm:"column:item_id;type:TEXT" json:"item_id"`
	Category string `gorm:"column:category;type:TEXT" json:"category"`
}

// TableName ItemCategories's table name
func (*ItemCategories) TableName() string {
	return TableNameItemCategories
}
