// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameItem = "item"

// Item mapped from table <item>
type Item struct {
	ID    string `gorm:"column:id;type:TEXT" json:"id"`
	Name  string `gorm:"column:name;type:TEXT" json:"name"`
	Value string `gorm:"column:value;type:TEXT" json:"value"`
	Price int32  `gorm:"column:price;type:INTEGER" json:"price"`
}

// TableName Item's table name
func (*Item) TableName() string {
	return TableNameItem
}
