// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameItemAdLinks = "item_ad_links"

// ItemAdLinks mapped from table <item_ad_links>
type ItemAdLinks struct {
	ItemID   string `gorm:"column:item_id;type:TEXT" json:"item_id"`
	AdLinkID string `gorm:"column:ad_link_id;type:TEXT" json:"ad_link_id"`
}

// TableName ItemAdLinks's table name
func (*ItemAdLinks) TableName() string {
	return TableNameItemAdLinks
}
