// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAdImage = "ad_image"

// AdImage mapped from table <ad_image>
type AdImage struct {
	ID   string `gorm:"column:id;type:TEXT" json:"id"`
	URL  string `gorm:"column:url;type:TEXT" json:"url"`
	Text string `gorm:"column:text" json:"text"`
}

// TableName AdImage's table name
func (*AdImage) TableName() string {
	return TableNameAdImage
}
