// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAdLink = "ad_link"

// AdLink mapped from table <ad_link>
type AdLink struct {
	ID   string `gorm:"column:id;type:TEXT" json:"id"`
	URL  string `gorm:"column:url;type:TEXT" json:"url"`
	Text string `gorm:"column:text;not null" json:"text"`
}

// TableName AdLink's table name
func (*AdLink) TableName() string {
	return TableNameAdLink
}
