// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameItemTags = "item_tags"

// ItemTags mapped from table <item_tags>
type ItemTags struct {
	ItemID string `gorm:"column:item_id;type:TEXT" json:"item_id"`
	TagID  string `gorm:"column:tag_id;type:TEXT" json:"tag_id"`
}

// TableName ItemTags's table name
func (*ItemTags) TableName() string {
	return TableNameItemTags
}
