// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTag = "tag"

// Tag mapped from table <tag>
type Tag struct {
	ID    string `gorm:"column:id;type:TEXT" json:"id"`
	Name  string `gorm:"column:name;type:TEXT" json:"name"`
	Value string `gorm:"column:value;not null" json:"value"`
}

// TableName Tag's table name
func (*Tag) TableName() string {
	return TableNameTag
}
