package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"

	graph "yujiorama.github.io/graphql-federation-test/app/new-service/graph/generated"
	"yujiorama.github.io/graphql-federation-test/app/new-service/graph/model"
)

// FindItemByID is the resolver for the findItemByID field.
func (r *entityResolver) FindItemByID(ctx context.Context, id string) (*model.Item, error) {
	return FindItemByID(id)
}

// Entity returns graph.EntityResolver implementation.
func (r *Resolver) Entity() graph.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
