package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.79

import (
	"context"
	"fmt"

	"yujiorama.github.io/graphql-federation-test/app/new-service/graph/generated"
	"yujiorama.github.io/graphql-federation-test/app/new-service/graph/model"
)

// GetItem is the resolver for the getItem field.
func (r *queryResolver) GetItem(ctx context.Context, itemID string) (*model.Item, error) {
	item, err := FindItemByID(ctx, itemID)
	if err != nil {
		return nil, fmt.Errorf("failed to find item with id: %s", itemID)
	}
	return item, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
