// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"yujiorama.github.io/graphql-federation-test/app/new-service/model"
)

func newItem(db *gorm.DB, opts ...gen.DOOption) item {
	_item := item{}

	_item.itemDo.UseDB(db, opts...)
	_item.itemDo.UseModel(&model.Item{})

	tableName := _item.itemDo.TableName()
	_item.ALL = field.NewAsterisk(tableName)
	_item.ID = field.NewString(tableName, "id")
	_item.Name = field.NewString(tableName, "name")
	_item.Value = field.NewString(tableName, "value")
	_item.Price = field.NewInt32(tableName, "price")

	_item.fillFieldMap()

	return _item
}

type item struct {
	itemDo

	ALL   field.Asterisk
	ID    field.String
	Name  field.String
	Value field.String
	Price field.Int32

	fieldMap map[string]field.Expr
}

func (i item) Table(newTableName string) *item {
	i.itemDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i item) As(alias string) *item {
	i.itemDo.DO = *(i.itemDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *item) updateTableName(table string) *item {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewString(table, "id")
	i.Name = field.NewString(table, "name")
	i.Value = field.NewString(table, "value")
	i.Price = field.NewInt32(table, "price")

	i.fillFieldMap()

	return i
}

func (i *item) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *item) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 4)
	i.fieldMap["id"] = i.ID
	i.fieldMap["name"] = i.Name
	i.fieldMap["value"] = i.Value
	i.fieldMap["price"] = i.Price
}

func (i item) clone(db *gorm.DB) item {
	i.itemDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i item) replaceDB(db *gorm.DB) item {
	i.itemDo.ReplaceDB(db)
	return i
}

type itemDo struct{ gen.DO }

type IItemDo interface {
	gen.SubQuery
	Debug() IItemDo
	WithContext(ctx context.Context) IItemDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IItemDo
	WriteDB() IItemDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IItemDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IItemDo
	Not(conds ...gen.Condition) IItemDo
	Or(conds ...gen.Condition) IItemDo
	Select(conds ...field.Expr) IItemDo
	Where(conds ...gen.Condition) IItemDo
	Order(conds ...field.Expr) IItemDo
	Distinct(cols ...field.Expr) IItemDo
	Omit(cols ...field.Expr) IItemDo
	Join(table schema.Tabler, on ...field.Expr) IItemDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IItemDo
	RightJoin(table schema.Tabler, on ...field.Expr) IItemDo
	Group(cols ...field.Expr) IItemDo
	Having(conds ...gen.Condition) IItemDo
	Limit(limit int) IItemDo
	Offset(offset int) IItemDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IItemDo
	Unscoped() IItemDo
	Create(values ...*model.Item) error
	CreateInBatches(values []*model.Item, batchSize int) error
	Save(values ...*model.Item) error
	First() (*model.Item, error)
	Take() (*model.Item, error)
	Last() (*model.Item, error)
	Find() ([]*model.Item, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Item, err error)
	FindInBatches(result *[]*model.Item, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Item) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IItemDo
	Assign(attrs ...field.AssignExpr) IItemDo
	Joins(fields ...field.RelationField) IItemDo
	Preload(fields ...field.RelationField) IItemDo
	FirstOrInit() (*model.Item, error)
	FirstOrCreate() (*model.Item, error)
	FindByPage(offset int, limit int) (result []*model.Item, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IItemDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i itemDo) Debug() IItemDo {
	return i.withDO(i.DO.Debug())
}

func (i itemDo) WithContext(ctx context.Context) IItemDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i itemDo) ReadDB() IItemDo {
	return i.Clauses(dbresolver.Read)
}

func (i itemDo) WriteDB() IItemDo {
	return i.Clauses(dbresolver.Write)
}

func (i itemDo) Session(config *gorm.Session) IItemDo {
	return i.withDO(i.DO.Session(config))
}

func (i itemDo) Clauses(conds ...clause.Expression) IItemDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i itemDo) Returning(value interface{}, columns ...string) IItemDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i itemDo) Not(conds ...gen.Condition) IItemDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i itemDo) Or(conds ...gen.Condition) IItemDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i itemDo) Select(conds ...field.Expr) IItemDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i itemDo) Where(conds ...gen.Condition) IItemDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i itemDo) Order(conds ...field.Expr) IItemDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i itemDo) Distinct(cols ...field.Expr) IItemDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i itemDo) Omit(cols ...field.Expr) IItemDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i itemDo) Join(table schema.Tabler, on ...field.Expr) IItemDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i itemDo) LeftJoin(table schema.Tabler, on ...field.Expr) IItemDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i itemDo) RightJoin(table schema.Tabler, on ...field.Expr) IItemDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i itemDo) Group(cols ...field.Expr) IItemDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i itemDo) Having(conds ...gen.Condition) IItemDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i itemDo) Limit(limit int) IItemDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i itemDo) Offset(offset int) IItemDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i itemDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IItemDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i itemDo) Unscoped() IItemDo {
	return i.withDO(i.DO.Unscoped())
}

func (i itemDo) Create(values ...*model.Item) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i itemDo) CreateInBatches(values []*model.Item, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i itemDo) Save(values ...*model.Item) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i itemDo) First() (*model.Item, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Item), nil
	}
}

func (i itemDo) Take() (*model.Item, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Item), nil
	}
}

func (i itemDo) Last() (*model.Item, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Item), nil
	}
}

func (i itemDo) Find() ([]*model.Item, error) {
	result, err := i.DO.Find()
	return result.([]*model.Item), err
}

func (i itemDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Item, err error) {
	buf := make([]*model.Item, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i itemDo) FindInBatches(result *[]*model.Item, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i itemDo) Attrs(attrs ...field.AssignExpr) IItemDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i itemDo) Assign(attrs ...field.AssignExpr) IItemDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i itemDo) Joins(fields ...field.RelationField) IItemDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i itemDo) Preload(fields ...field.RelationField) IItemDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i itemDo) FirstOrInit() (*model.Item, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Item), nil
	}
}

func (i itemDo) FirstOrCreate() (*model.Item, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Item), nil
	}
}

func (i itemDo) FindByPage(offset int, limit int) (result []*model.Item, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i itemDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i itemDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i itemDo) Delete(models ...*model.Item) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *itemDo) withDO(do gen.Dao) *itemDo {
	i.DO = *do.(*gen.DO)
	return i
}
