version: 1
subgraphs:
  - name: current-service
    routing_url: http://current-service:4001/graphql
    schema:
      file: ./graph/current-service.graphqls
  - name: new-service
    routing_url: http://new-service:4002/graphql
    schema:
      file: ./graph/new-service.graphqls
