// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Item struct {
	ID     string `json:"id"`
	Number *int32 `json:"number,omitempty"`
}

func (Item) IsEntity() {}

type Query struct {
}
